import type { Metadata } from "next";
import "./globals.css";
import { AppKitProvider } from "@/components/providers/appkit-provider";
import { headers } from "next/headers";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: { children: ReactNode }) {
  const cookies = (await headers()).get("cookie") as string | null;

  return (
    <html lang="en">
      <body>
        <AppKitProvider cookies={cookies}>{props.children}</AppKitProvider>
      </body>
    </html>
  );
}
